import sqlite3
import hashlib
import os
from datetime import datetime

class EventStateManager:
    """
    SQLite-based Singleton Repository tracking previously published content.
    Prevents duplicate pipeline dispatches on back-to-back crontab fires.
    """
    def __init__(self, db_path="/Users/lillianliao/notion_rag/universal_content_orchestrator/data/events.db"):
        self.db_path = db_path
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self._init_db()

    def _init_db(self):
        with sqlite3.connect(self.db_path) as conn:
            # 老库格式保留用于兼容读取
            conn.execute('''
                CREATE TABLE IF NOT EXISTS processed_events (
                    hash_id TEXT PRIMARY KEY,
                    title TEXT,
                    source TEXT,
                    timestamp TEXT
                )
            ''')
            # 建立多端追踪明细新表 (联合主键)
            conn.execute('''
                CREATE TABLE IF NOT EXISTS publish_log (
                    hash_id TEXT,
                    platform TEXT,
                    timestamp TEXT,
                    PRIMARY KEY (hash_id, platform)
                )
            ''')
            # 建立管线全局执行历史表（监控漏斗）
            conn.execute('''
                CREATE TABLE IF NOT EXISTS pipeline_run_history (
                    run_id TEXT PRIMARY KEY,
                    pipeline_id TEXT,
                    start_time TEXT,
                    end_time TEXT,
                    items_scraped INTEGER,
                    items_passed_llm INTEGER,
                    drafts_generated INTEGER,
                    status TEXT
                )
            ''')
            # 建立人工审核草稿箱
            conn.execute('''
                CREATE TABLE IF NOT EXISTS content_drafts (
                    draft_id TEXT PRIMARY KEY,
                    pipeline_id TEXT,
                    hash_id TEXT,
                    title TEXT,
                    markdown_body TEXT,
                    status TEXT,
                    created_at TEXT
                )
            ''')

    def _get_hash(self, event):
        # URLs are the most stable identifiers across Hackernews and RSS plugins
        return hashlib.md5(event.url.encode('utf-8')).hexdigest()

    def is_processed(self, event, platform: str) -> bool:
        """Evaluate if the article has been rendered and posted successfully to a SPECIFIC platform."""
        hash_id = self._get_hash(event)
        with sqlite3.connect(self.db_path) as conn:
            # 向后兼容：如果存在于历史表里，则默认全部分散端点已发出
            cursor = conn.execute("SELECT 1 FROM processed_events WHERE hash_id=?", (hash_id,))
            if cursor.fetchone() is not None:
                return True
                
            # 2. 如果存在于草稿箱，无论是否发布，都视为已被系统收录，防止明天再次抓取浪费 LLM 资源
            cursor = conn.execute("SELECT 1 FROM content_drafts WHERE hash_id=?", (hash_id,))
            if cursor.fetchone() is not None:
                return True
                
            # 3. 检查单端点发布历史
            cursor = conn.execute("SELECT 1 FROM publish_log WHERE hash_id=? AND platform=?", (hash_id, platform))
            return cursor.fetchone() is not None

    def mark_success(self, event, platform: str):
        """Permanent flush to DB ensuring future runs will ignore this content FOR A SPECIFIC PLATFORM."""
        hash_id = self._get_hash(event)
        with sqlite3.connect(self.db_path) as conn:
            conn.execute('''
                INSERT OR REPLACE INTO publish_log (hash_id, platform, timestamp)
                VALUES (?, ?, ?)
            ''', (hash_id, platform, datetime.now().isoformat()))

    def create_pipeline_run(self, run_id: str, pipeline_id: str):
        """Log the start of a pipeline run to track funnel metrics."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute('''
                INSERT INTO pipeline_run_history (run_id, pipeline_id, start_time, status)
                VALUES (?, ?, ?, 'RUNNING')
            ''', (run_id, pipeline_id, datetime.now().isoformat()))

    def update_pipeline_run(self, run_id: str, items_scraped: int, items_passed_llm: int, drafts_generated: int, status: str):
        """Finalize funnel metrics when the pipeline finishes."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute('''
                UPDATE pipeline_run_history
                SET end_time=?, items_scraped=?, items_passed_llm=?, drafts_generated=?, status=?
                WHERE run_id=?
            ''', (datetime.now().isoformat(), items_scraped, items_passed_llm, drafts_generated, status, run_id))

    def save_draft(self, draft_id: str, pipeline_id: str, event, title: str, markdown_body: str):
        """Save intercepted content generated by LLM into isolated draft inbox."""
        hash_id = self._get_hash(event)
        with sqlite3.connect(self.db_path) as conn:
            conn.execute('''
                INSERT OR REPLACE INTO content_drafts (draft_id, pipeline_id, hash_id, title, markdown_body, status, created_at)
                VALUES (?, ?, ?, ?, ?, 'PENDING', ?)
            ''', (draft_id, pipeline_id, hash_id, title, markdown_body, datetime.now().isoformat()))
