import urllib.request
import json
from typing import List, Dict, Any
from core.schemas import RawContentEvent
from sources.base_source import BaseSourceAdapter

class TrendRadarAdapter(BaseSourceAdapter):
    """
    Adapter bridging the lightweight TrendRadar AI News Aggregator
    into the Universal Content Orchestrator's internal event bus.
    It fetches pre-filtered, AI-summarized JSON payloads pushed by TrendRadar.
    """
    def __init__(self, endpoint_url: str = "http://localhost:3333/api/v1/news?limit=10"):
        # Expecting TrendRadar to run as a separate macro-service (e.g. MCP Server or simple JSON wrapper)
        self.endpoint_url = endpoint_url

    def fetch(self, limit: int = 10) -> List[RawContentEvent]:
        print(f"📡 [Target: TrendRadar] 发起主动解耦拉取，探测顶级风向标...")
        events = []
        
        # This is a mockup of the payload expected. If TrendRadar SQLite is local, you can also use sqlite3.
        # But fetching via HTTP MCP is cleaner architecturally.
        try:
            req = urllib.request.Request(self.endpoint_url)
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = json.loads(resp.read().decode('utf-8'))
                
                # Assume data['items'] is the payload from TrendRadar
                items = data.get('items', [])
                
                for item in items[:limit]:
                    events.append(RawContentEvent(
                        id=item.get('hash_id', 'unknown_id'),
                        source_channel=f"trendradar_{item.get('platform', 'rss')}",
                        title=item.get('title', 'No Title'),
                        # Merge the AI summary generated by TrendRadar directly into the raw content
                        content=f"{item.get('summary', '')}\\n\\n[AI Analysis]: {item.get('ai_analysis', 'None')}",
                        url=item.get('link', '')
                    ))
                    
            print(f"✅ [Source: TrendRadar] 成功截获并封印 {len(events)} 篇 AI 初筛热点。")
            
        except Exception as e:
            print(f"⚠️ [Source: TrendRadar] 雷达掉线或未开启服务, 回退机制已就绪: {e}")
            
        return events
